### ISSUE TITLE
`timeFormatDefaultLocale` to change month abbreviations breaks the calendar

### ISSUE THREAD

**Issue by maiconcarraro** [jquintozamora/react-d3-calendar-heatmap#1]
`formatDay` allows to change the day of week, but there is no function to manipulate the month abbreviation, I tried to change through d3 import and it breaks the calendar. What should be the correct path to achieve this? Should I work in a PR to support `formatMonth`?

**Comment by jquintozamora** [comment]
Thanks for your input @maiconcarraro , merged
